### ISSUE TITLE
Тест на пустые логин-пароль

### ISSUE THREAD

**Issue by dw-elena** [15141415/nf_test#1]
Поймать сообщение об ошибке при пустых полях

**Comment by ame-ne** [comment]
```c#
using OpenQA.Selenium.Interactions;
...
[TestCase]
public void TestMethod1()
{
    driver.FindElement(By.Id("UserName")).Submit();
    Actions act = new Actions(driver);
    act.MoveToElement(driver.FindElement(By.Id("UserName"))).Perform();
    Assert.IsTrue(driver.FindElement(By.Id("UserName-error")).Displayed);
    act.MoveToElement(driver.FindElement(By.Id("Password"))).Perform(); 
    Assert.IsTrue(driver.FindElement(By.Id("Password-error")).Displayed);
}
```
В хроме проходит, в лисе нет(и самих сообщений нет)
А ещё картинка http://урл/Images/Icons/validationError.png потерялась. Дважды.

**Comment by dw-elena** [comment]
Да, картинка и у меня не открывается - баг?
Title'а для страницы входа нет - баг?
И сообщение в лисе не отображаются - баг?
Я правильно понимаю, что .Displayed возвращает отображён ли элемент пользователю? Потому что на странице он уже присутствует в разметке (всегда), а отображается javascript'ом (или это относится к чудесам html5)?
Кстати, можешь добавить строки в мой файл (можно ещё и id для сообщений включить в LoginPage) и закрыть issue. Не зря же у нас командный проект

**Comment by ame-ne** [comment]
Да.
Да.
Да.
~~не баг, а инцидент~~
Да, проверяется именно видимость на странице, а не наличие в коде.
Неа, сама добавляй. Я тут что-то шатаю... :fearful: 
*закрыть issue*
а... т.е. это не чатик? :cry:

**Comment by dw-elena** [comment]
issue - англ. - проблема. ладно, добавлю и закрою

**Comment by ame-ne** [comment]
Проблема -> обсуждение -> чатик :octocat:

**Comment by dw-elena** [comment]
У меня всё ещё не получается :(
<input data-val="true" data-val-required="Требуется поле Имя пользователя." id="UserName" name="UserName" type="text" value="" />
Нет отдельного элемента (с отдельным id) с сообщением
